# Generated by Django 2.2.4 on 2019-09-18 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_delete_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='description',
            field=models.CharField(default='..', max_length=300),
            preserve_default=False,
        ),
    ]
